---
# tasks file for CVE-2018-19788

- name: Provision a unprivileged user with UID greater than 2147483647
  block:
  - name:  Add the 'cve_test' account
    user:
      name: cve_test
      comment: Test for CVE-2018-19788
      uid: 2147483649

- name: Exploit the CVE-2018-19788
  block:
  - name: Push the PoC exploit code
    copy:
      src: ./CVE-2018-19788-PoC.sh
      dest: "$HOME/CVE-2018-19788-PoC.sh"
      owner: cve_test
      group: cve_test
      mode: 650
  become: True
  become_user: cve_test

# - name: Output a list of users
#   shell: getent passwd | awk -F: '$3 >= 2147483647 {print $1}'
#   register: users_list

# - name: Debug
#   debug:
#     msg: "{{ users_list }}"
#   when: users_list is defined